"""add team_members table

Revision ID: c1877597555c
Revises: d7f4a8c9210e
Create Date: 2026-08-20 21:50:56.832161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1877597555c'
down_revision: Union[str, Sequence[str], None] = 'd7f4a8c9210e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_live_codes_active_project'), table_name='live_codes', sqlite_where=sa.text('project_id IS NOT NULL AND is_deleted = 0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_live_codes_active_project'), 'live_codes', ['project_id'], unique=1, sqlite_where=sa.text('project_id IS NOT NULL AND is_deleted = 0'))
    # ### end Alembic commands ###
